2024-03-12 20:04:45,629 INFO    StreamThr :5024 [internal.py:wandb_internal():86] W&B internal server running at pid: 5024, started at: 2024-03-12 20:04:45.628757
2024-03-12 20:04:45,630 DEBUG   HandlerThread:5024 [handler.py:handle_request():146] handle_request: status
2024-03-12 20:04:45,633 INFO    WriterThread:5024 [datastore.py:open_for_write():87] open: /home/danielcarias/Documents/Estudo NN/Estudo/CNN/first_project/wandb/run-20240312_200445-68mehvfi/run-68mehvfi.wandb
2024-03-12 20:04:45,634 DEBUG   SenderThread:5024 [sender.py:send():378] send: header
2024-03-12 20:04:45,634 DEBUG   SenderThread:5024 [sender.py:send():378] send: run
2024-03-12 20:04:46,136 INFO    SenderThread:5024 [dir_watcher.py:__init__():211] watching files in: /home/danielcarias/Documents/Estudo NN/Estudo/CNN/first_project/wandb/run-20240312_200445-68mehvfi/files
2024-03-12 20:04:46,136 INFO    SenderThread:5024 [sender.py:_start_run_threads():1099] run started: 68mehvfi with start time 1710273885.628892
2024-03-12 20:04:46,148 DEBUG   HandlerThread:5024 [handler.py:handle_request():146] handle_request: check_version
2024-03-12 20:04:46,149 DEBUG   SenderThread:5024 [sender.py:send_request():405] send_request: check_version
2024-03-12 20:04:46,289 DEBUG   HandlerThread:5024 [handler.py:handle_request():146] handle_request: run_start
2024-03-12 20:04:46,310 DEBUG   HandlerThread:5024 [system_info.py:__init__():26] System info init
2024-03-12 20:04:46,310 DEBUG   HandlerThread:5024 [system_info.py:__init__():41] System info init done
2024-03-12 20:04:46,310 INFO    HandlerThread:5024 [system_monitor.py:start():194] Starting system monitor
2024-03-12 20:04:46,311 INFO    SystemMonitor:5024 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-03-12 20:04:46,311 INFO    HandlerThread:5024 [system_monitor.py:probe():214] Collecting system info
2024-03-12 20:04:46,311 INFO    SystemMonitor:5024 [interfaces.py:start():190] Started cpu monitoring
2024-03-12 20:04:46,312 INFO    SystemMonitor:5024 [interfaces.py:start():190] Started disk monitoring
2024-03-12 20:04:46,312 INFO    SystemMonitor:5024 [interfaces.py:start():190] Started gpu monitoring
2024-03-12 20:04:46,313 INFO    SystemMonitor:5024 [interfaces.py:start():190] Started memory monitoring
2024-03-12 20:04:46,314 INFO    SystemMonitor:5024 [interfaces.py:start():190] Started network monitoring
2024-03-12 20:04:46,320 DEBUG   HandlerThread:5024 [system_info.py:probe():150] Probing system
2024-03-12 20:04:46,322 DEBUG   HandlerThread:5024 [gitlib.py:_init_repo():56] git repository is invalid
2024-03-12 20:04:46,322 DEBUG   HandlerThread:5024 [system_info.py:probe():198] Probing system done
2024-03-12 20:04:46,322 DEBUG   HandlerThread:5024 [system_monitor.py:probe():223] {'os': 'Linux-6.6.10-76060610-generic-x86_64-with-glibc2.35', 'python': '3.10.12', 'heartbeatAt': '2024-03-12T20:04:46.320924', 'startedAt': '2024-03-12T20:04:45.619953', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '/home/danielcarias/Documents/Estudo NN/Estudo/CNN/first_project/CNN.py', 'codePathLocal': 'CNN.py', 'codePath': 'CNN.py', 'host': 'pop-os', 'username': 'danielcarias', 'executable': '/usr/bin/python', 'cpu_count': 6, 'cpu_count_logical': 12, 'cpu_freq': {'current': 2953.9606666666664, 'min': 1400.0, 'max': 3000.0}, 'cpu_freq_per_core': [{'current': 1771.138, 'min': 1400.0, 'max': 3000.0}, {'current': 1774.719, 'min': 1400.0, 'max': 3000.0}, {'current': 2482.189, 'min': 1400.0, 'max': 3000.0}, {'current': 2721.35, 'min': 1400.0, 'max': 3000.0}, {'current': 3979.2, 'min': 1400.0, 'max': 3000.0}, {'current': 3980.299, 'min': 1400.0, 'max': 3000.0}, {'current': 1774.332, 'min': 1400.0, 'max': 3000.0}, {'current': 1774.148, 'min': 1400.0, 'max': 3000.0}, {'current': 2051.842, 'min': 1400.0, 'max': 3000.0}, {'current': 2538.79, 'min': 1400.0, 'max': 3000.0}, {'current': 3822.752, 'min': 1400.0, 'max': 3000.0}, {'current': 3990.061, 'min': 1400.0, 'max': 3000.0}], 'disk': {'/': {'total': 459.5223274230957, 'used': 118.56354522705078}}, 'gpu': 'NVIDIA GeForce GTX 1650', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce GTX 1650', 'memory_total': 4294967296}], 'memory': {'total': 14.997817993164062}}
2024-03-12 20:04:46,322 INFO    HandlerThread:5024 [system_monitor.py:probe():224] Finished collecting system info
2024-03-12 20:04:46,322 INFO    HandlerThread:5024 [system_monitor.py:probe():227] Publishing system info
2024-03-12 20:04:46,323 INFO    HandlerThread:5024 [system_monitor.py:probe():229] Finished publishing system info
2024-03-12 20:04:46,326 DEBUG   SenderThread:5024 [sender.py:send():378] send: files
2024-03-12 20:04:46,327 INFO    SenderThread:5024 [sender.py:_save_file():1365] saving file wandb-metadata.json with policy now
2024-03-12 20:04:46,432 DEBUG   HandlerThread:5024 [handler.py:handle_request():146] handle_request: python_packages
2024-03-12 20:04:46,432 DEBUG   SenderThread:5024 [sender.py:send_request():405] send_request: python_packages
2024-03-12 20:04:46,476 DEBUG   HandlerThread:5024 [handler.py:handle_request():146] handle_request: stop_status
2024-03-12 20:04:46,476 DEBUG   HandlerThread:5024 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-12 20:04:46,477 DEBUG   SenderThread:5024 [sender.py:send_request():405] send_request: stop_status
2024-03-12 20:04:46,853 DEBUG   SenderThread:5024 [sender.py:send():378] send: telemetry
2024-03-12 20:04:47,073 INFO    wandb-upload_0:5024 [upload_job.py:push():131] Uploaded file /tmp/tmpddvcs9_wwandb/k0mfsg2s-wandb-metadata.json
2024-03-12 20:04:47,137 INFO    Thread-12 :5024 [dir_watcher.py:_on_file_created():271] file/dir created: /home/danielcarias/Documents/Estudo NN/Estudo/CNN/first_project/wandb/run-20240312_200445-68mehvfi/files/wandb-metadata.json
2024-03-12 20:04:47,138 INFO    Thread-12 :5024 [dir_watcher.py:_on_file_created():271] file/dir created: /home/danielcarias/Documents/Estudo NN/Estudo/CNN/first_project/wandb/run-20240312_200445-68mehvfi/files/output.log
2024-03-12 20:04:47,138 INFO    Thread-12 :5024 [dir_watcher.py:_on_file_created():271] file/dir created: /home/danielcarias/Documents/Estudo NN/Estudo/CNN/first_project/wandb/run-20240312_200445-68mehvfi/files/requirements.txt
2024-03-12 20:04:49,137 INFO    Thread-12 :5024 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/danielcarias/Documents/Estudo NN/Estudo/CNN/first_project/wandb/run-20240312_200445-68mehvfi/files/output.log
2024-03-12 20:04:51,200 DEBUG   HandlerThread:5024 [handler.py:handle_request():146] handle_request: status_report
2024-03-12 20:04:56,201 DEBUG   HandlerThread:5024 [handler.py:handle_request():146] handle_request: status_report
2024-03-12 20:05:01,433 DEBUG   HandlerThread:5024 [handler.py:handle_request():146] handle_request: stop_status
2024-03-12 20:05:01,433 DEBUG   SenderThread:5024 [sender.py:send_request():405] send_request: stop_status
2024-03-12 20:05:01,434 DEBUG   HandlerThread:5024 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-12 20:05:01,718 DEBUG   HandlerThread:5024 [handler.py:handle_request():146] handle_request: status_report
2024-03-12 20:05:03,141 INFO    Thread-12 :5024 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/danielcarias/Documents/Estudo NN/Estudo/CNN/first_project/wandb/run-20240312_200445-68mehvfi/files/output.log
2024-03-12 20:05:06,718 DEBUG   HandlerThread:5024 [handler.py:handle_request():146] handle_request: status_report
2024-03-12 20:05:11,720 DEBUG   HandlerThread:5024 [handler.py:handle_request():146] handle_request: status_report
2024-03-12 20:05:15,131 ERROR   FileStreamThread:5024 [file_stream.py:_handle_response():504] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/multitudinous/FashionMNIST/68mehvfi/file_stream
NoneType: None
2024-03-12 20:05:15,145 INFO    Thread-12 :5024 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/danielcarias/Documents/Estudo NN/Estudo/CNN/first_project/wandb/run-20240312_200445-68mehvfi/files/output.log
2024-03-12 20:05:16,433 DEBUG   HandlerThread:5024 [handler.py:handle_request():146] handle_request: stop_status
2024-03-12 20:05:16,433 DEBUG   SenderThread:5024 [sender.py:send_request():405] send_request: stop_status
2024-03-12 20:05:16,434 DEBUG   HandlerThread:5024 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-12 20:05:17,672 DEBUG   HandlerThread:5024 [handler.py:handle_request():146] handle_request: status_report
2024-03-12 20:05:17,833 ERROR   SenderThread:5024 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-03-12 20:05:17,833 ERROR   SenderThread:5024 [internal_api.py:execute():374] {"errors":[{"message":"run multitudinous/FashionMNIST/68mehvfi was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-03-12 20:05:19,129 ERROR   SenderThread:5024 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-03-12 20:05:19,129 ERROR   SenderThread:5024 [internal_api.py:execute():374] {"errors":[{"message":"run multitudinous/FashionMNIST/68mehvfi was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-03-12 20:05:21,398 ERROR   SenderThread:5024 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-03-12 20:05:21,398 ERROR   SenderThread:5024 [internal_api.py:execute():374] {"errors":[{"message":"run multitudinous/FashionMNIST/68mehvfi was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-03-12 20:05:21,398 INFO    SenderThread:5024 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/danielcarias/.local/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/danielcarias/.local/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/danielcarias/.local/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/danielcarias/.local/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/danielcarias/.local/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql
2024-03-12 20:05:26,119 ERROR   SenderThread:5024 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-03-12 20:05:26,119 ERROR   SenderThread:5024 [internal_api.py:execute():374] {"errors":[{"message":"run multitudinous/FashionMNIST/68mehvfi was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-03-12 20:05:31,433 DEBUG   HandlerThread:5024 [handler.py:handle_request():146] handle_request: stop_status
2024-03-12 20:05:31,433 DEBUG   HandlerThread:5024 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-12 20:05:35,820 ERROR   SenderThread:5024 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-03-12 20:05:35,820 ERROR   SenderThread:5024 [internal_api.py:execute():374] {"errors":[{"message":"run multitudinous/FashionMNIST/68mehvfi was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-03-12 20:05:37,014 DEBUG   HandlerThread:5024 [handler.py:handle_request():146] handle_request: poll_exit
2024-03-12 20:05:42,015 DEBUG   HandlerThread:5024 [handler.py:handle_request():146] handle_request: keepalive
2024-03-12 20:05:46,314 DEBUG   SystemMonitor:5024 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-03-12 20:05:47,017 DEBUG   HandlerThread:5024 [handler.py:handle_request():146] handle_request: keepalive
2024-03-12 20:05:52,019 DEBUG   HandlerThread:5024 [handler.py:handle_request():146] handle_request: keepalive
2024-03-12 20:05:53,022 ERROR   SenderThread:5024 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-03-12 20:05:53,022 ERROR   SenderThread:5024 [internal_api.py:execute():374] {"errors":[{"message":"run multitudinous/FashionMNIST/68mehvfi was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-03-12 20:05:57,021 DEBUG   HandlerThread:5024 [handler.py:handle_request():146] handle_request: keepalive
2024-03-12 20:06:02,023 DEBUG   HandlerThread:5024 [handler.py:handle_request():146] handle_request: keepalive
2024-03-12 20:06:04,346 INFO    memory    :5024 [interfaces.py:monitor():140] Process proc.memory.rssMB has exited.
2024-03-12 20:06:04,347 DEBUG   SystemMonitor:5024 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-03-12 20:06:04,347 DEBUG   SystemMonitor:5024 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-03-12 20:06:06,863 WARNING StreamThr :5024 [internal.py:is_dead():414] Internal process exiting, parent pid 4855 disappeared
2024-03-12 20:06:06,863 ERROR   StreamThr :5024 [internal.py:wandb_internal():152] Internal process shutdown.
2024-03-12 20:06:07,025 DEBUG   HandlerThread:5024 [handler.py:handle_request():146] handle_request: keepalive
2024-03-12 20:06:07,025 INFO    HandlerThread:5024 [handler.py:finish():869] shutting down handler
2024-03-12 20:06:07,025 INFO    HandlerThread:5024 [system_monitor.py:finish():203] Stopping system monitor
2024-03-12 20:06:07,025 INFO    HandlerThread:5024 [interfaces.py:finish():202] Joined cpu monitor
2024-03-12 20:06:07,025 INFO    HandlerThread:5024 [interfaces.py:finish():202] Joined disk monitor
2024-03-12 20:06:07,025 INFO    HandlerThread:5024 [interfaces.py:finish():202] Joined gpu monitor
2024-03-12 20:06:07,025 INFO    HandlerThread:5024 [interfaces.py:finish():202] Joined memory monitor
2024-03-12 20:06:07,026 INFO    HandlerThread:5024 [interfaces.py:finish():202] Joined network monitor
2024-03-12 20:06:07,350 INFO    WriterThread:5024 [datastore.py:close():296] close: /home/danielcarias/Documents/Estudo NN/Estudo/CNN/first_project/wandb/run-20240312_200445-68mehvfi/run-68mehvfi.wandb
2024-03-12 20:06:27,856 ERROR   SenderThread:5024 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-03-12 20:06:27,856 ERROR   SenderThread:5024 [internal_api.py:execute():374] {"errors":[{"message":"run multitudinous/FashionMNIST/68mehvfi was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-03-12 20:07:34,451 ERROR   SenderThread:5024 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-03-12 20:07:34,451 ERROR   SenderThread:5024 [internal_api.py:execute():374] {"errors":[{"message":"run multitudinous/FashionMNIST/68mehvfi was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-03-12 20:07:34,451 ERROR   StreamThr :5024 [internal.py:wandb_internal():174] Thread SenderThread:
Traceback (most recent call last):
  File "/home/danielcarias/.local/lib/python3.10/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/danielcarias/.local/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2216, in upsert_run
    response = self.gql(
  File "/home/danielcarias/.local/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 341, in gql
    ret = self._retry_gql(
  File "/home/danielcarias/.local/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/danielcarias/.local/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/danielcarias/.local/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/danielcarias/.local/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/danielcarias/.local/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/danielcarias/.local/lib/python3.10/site-packages/wandb/sdk/internal/internal_util.py", line 49, in run
    self._run()
  File "/home/danielcarias/.local/lib/python3.10/site-packages/wandb/sdk/internal/internal_util.py", line 93, in _run
    self._debounce()
  File "/home/danielcarias/.local/lib/python3.10/site-packages/wandb/sdk/internal/internal.py", line 334, in _debounce
    self._sm.debounce()
  File "/home/danielcarias/.local/lib/python3.10/site-packages/wandb/sdk/internal/sender.py", line 536, in debounce
    self._maybe_update_config(always=final)
  File "/home/danielcarias/.local/lib/python3.10/site-packages/wandb/sdk/internal/sender.py", line 513, in _maybe_update_config
    self._debounce_config()
  File "/home/danielcarias/.local/lib/python3.10/site-packages/wandb/sdk/internal/sender.py", line 542, in _debounce_config
    self._api.upsert_run(
  File "/home/danielcarias/.local/lib/python3.10/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: run multitudinous/FashionMNIST/68mehvfi was previously created and deleted; try a new run name (Error 409: Conflict)
