Dataset: ./data/cats_dogs_full/train and ./data/cats_dogs_full/test
Train dataloader: 624 batches
Test dataloader: 157 batches
--------Epoch: 0
-Training...
Batch: 0/624
/home/danielcarias/.local/lib/python3.10/site-packages/PIL/TiffImagePlugin.py:870: UserWarning: Truncated File Read
  warnings.warn(str(msg))
Batch: 400/624
Per batch -> Train Loss: 0.8128672242164612 | Train Accuracy: 50.02%
-Testing...
Batch: 0/157
Batch: 50/157
Batch: 100/157
Batch: 150/157
Traceback (most recent call last):
  File "/home/danielcarias/Documents/Estudo NN/Estudo/CNN/first_project/CNN.py", line 157, in <module>
    test_loss, test_acc = test_model(model, test_dataloader, loss_fn)
  File "/home/danielcarias/Documents/Estudo NN/Estudo/CNN/first_project/CNN.py", line 100, in test_model
    test_acc += accuracy_fn(y, test_pred)
  File "/home/danielcarias/Documents/Estudo NN/Estudo/CNN/first_project/utils.py", line 22, in accuracy_fn
    acc = (correct / len(y_pred)) * 100
  File "/home/danielcarias/.local/lib/python3.10/site-packages/torch/_tensor.py", line 1000, in __len__
    raise TypeError("len() of a 0-d tensor")
TypeError: len() of a 0-d tensor
Traceback (most recent call last):
  File "/home/danielcarias/Documents/Estudo NN/Estudo/CNN/first_project/CNN.py", line 157, in <module>
    test_loss, test_acc = test_model(model, test_dataloader, loss_fn)
  File "/home/danielcarias/Documents/Estudo NN/Estudo/CNN/first_project/CNN.py", line 100, in test_model
    test_acc += accuracy_fn(y, test_pred)
  File "/home/danielcarias/Documents/Estudo NN/Estudo/CNN/first_project/utils.py", line 22, in accuracy_fn
    acc = (correct / len(y_pred)) * 100
  File "/home/danielcarias/.local/lib/python3.10/site-packages/torch/_tensor.py", line 1000, in __len__
    raise TypeError("len() of a 0-d tensor")
TypeError: len() of a 0-d tensor